title: A discovery
author: Me
email: linus-bjorklund@live.se
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is an awsome description.
  

# social links
twitter_username: LinusBjrklund # DO NOT include the @ character, or else the build will fail!
github_username:  linusaprogrammer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
